# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1475905274);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1475905394);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1475593758);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1475905154);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1475905034);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1475905514);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 38);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.google.lastupdatetime", "1475905260227");
user_pref("browser.safebrowsing.provider.google.nextupdatetime", "1475907148227");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1475904944498");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1475908544498");
user_pref("browser.search.countryCode", "CN");
user_pref("browser.search.region", "CN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20160919213722");
user_pref("browser.slowStartup.averageTime", 18705);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20160919213722");
user_pref("browser.startup.homepage_override.mstone", "49.0");
user_pref("browser.tabs.remote.autostart.2", true);
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\",\"sync-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"downloads-button\",\"home-button\",\"pocket-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":6,\"newElementCount\":0}");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1475680037681");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1475593710711");
user_pref("datareporting.policy.firstRunTime", "1475593637680");
user_pref("datareporting.sessions.current.activeTicks", 8);
user_pref("datareporting.sessions.current.firstPaint", 23529);
user_pref("datareporting.sessions.current.main", 2332);
user_pref("datareporting.sessions.current.sessionRestored", 50231);
user_pref("datareporting.sessions.current.startTime", "1475904885991");
user_pref("datareporting.sessions.current.totalTime", 185);
user_pref("datareporting.sessions.currentIndex", 1);
user_pref("datareporting.sessions.previous.0", "{\"s\":1475593631829,\"a\":20,\"t\":170,\"c\":true,\"m\":1178,\"fp\":17671,\"sr\":18925}");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.apps.lastUpdate.buildID", "20160919213722");
user_pref("dom.apps.lastUpdate.mstone", "49.0");
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("e10s.rollout.cohort", "disqualified-test");
user_pref("e10s.rollout.cohortSample", "0.943984");
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.bootstrappedAddons", "{\"e10srollout@mozilla.org\":{\"version\":\"1.2\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox/browser/features/e10srollout@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true},\"firefox@getpocket.com\":{\"version\":\"1.0.4\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox/browser/features/firefox@getpocket.com.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true},\"webcompat@mozilla.org\":{\"version\":\"1.0\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox/browser/features/webcompat@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true},\"langpack-en-ZA@firefox.mozilla.org\":{\"version\":\"49.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"runInSafeMode\":false},\"langpack-en-GB@firefox.mozilla.org\":{\"version\":\"49.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"runInSafeMode\":false},\"firefox-hotfix@mozilla.org\":{\"version\":\"20160826.01\",\"type\":\"extension\",\"descriptor\":\"/home/zhang/.mozilla/firefox/a9q06hw0.default/extensions/firefox-hotfix@mozilla.org.xpi\",\"multiprocessCompatible\":true,\"runInSafeMode\":false}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.e10s.rollout.hasAddon", false);
user_pref("extensions.e10s.rollout.policy", "49a");
user_pref("extensions.e10sBlockedByAddons", true);
user_pref("extensions.enabledAddons", "ubufox%40ubuntu.com:3.2,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:49.0");
user_pref("extensions.getAddons.cache.lastUpdate", 1475905278);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20160826.01");
user_pref("extensions.lastAppVersion", "49.0");
user_pref("extensions.lastPlatformVersion", "49.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{3139bfb1-4d41-477f-8573-e2fee6f38cf7}\",\"addons\":{\"e10srollout@mozilla.org\":{\"version\":\"1.3\"}}}");
user_pref("extensions.xpiState", "{\"app-system-defaults\":{\"e10srollout@mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/features/e10srollout@mozilla.org.xpi\",\"e\":true,\"v\":\"1.2\",\"st\":1474324299000},\"firefox@getpocket.com\":{\"d\":\"/usr/lib/firefox/browser/features/firefox@getpocket.com.xpi\",\"e\":true,\"v\":\"1.0.4\",\"st\":1474324299000},\"webcompat@mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/features/webcompat@mozilla.org.xpi\",\"e\":true,\"v\":\"1.0\",\"st\":1474324299000}},\"app-global\":{\"langpack-en-ZA@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"49.0\",\"st\":1474324637000},\"langpack-en-GB@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"49.0\",\"st\":1474324637000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"49.0\",\"st\":1474324299000}},\"app-system-share\":{\"ubufox@ubuntu.com\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com.xpi\",\"e\":true,\"v\":\"3.2\",\"st\":1442597111000}}}");
user_pref("gecko.buildID", "20160209234718");
user_pref("gecko.mstone", "44.0.2");
user_pref("idle.lastDailyNotification", 1475905580);
user_pref("media.gmp-gmpopenh264.abi", "x86-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1475904997);
user_pref("media.gmp-gmpopenh264.version", "1.6");
user_pref("media.gmp-manager.buildID", "20160919213722");
user_pref("media.gmp-manager.lastCheck", 1475904996);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 26220);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateClearSavedPwdsOnExit", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("toolkit.startup.last_success", 1475904888);
user_pref("toolkit.telemetry.cachedClientID", "bfb344d9-322c-4119-9cfe-37a7d59c8dc4");
user_pref("toolkit.telemetry.previousBuildID", "20160919213722");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
